import { GENERATED_PACKAGE_NAME, GENERATED_PACKAGE_VERSION } from "./package-info.generated.js";

export const OPENCODE_PLUSPLUS_PACKAGE_NAME = GENERATED_PACKAGE_NAME;
export const OPENCODE_PLUSPLUS_PACKAGE_VERSION = GENERATED_PACKAGE_VERSION;

export function getOpenCodePlusplusPackageVersion(): string {
  return OPENCODE_PLUSPLUS_PACKAGE_VERSION;
}
